window.LLineMockData = {
  user: {
    name: "Daniel Garcia",
    email: "daniel.garcia@lline.app",
    role: "user",
    avatar: "DG",
    vehicles: [
      { model: "Tesla Model 3", battery: "75 kWh", plate: "1234-LLE" },
      { model: "Hyundai IONIQ 5", battery: "72.6 kWh", plate: "8891-ELX" }
    ],
    preferences: {
      notifyReservation: true,
      notifyNearbyFree: true,
      darkMap: false
    }
  },
  chargers: [
    {
      id: "chg-001",
      name: "Parking Norte",
      address: "Av. Europa 18, Murcia",
      lat: 37.9928,
      lng: -1.1307,
      status: "libre",
      type: "rapido",
      power: 150,
      price: 0.29,
      distance: 1.2,
      eta: "28 min",
      schedule: "24/7",
      connectors: "CCS, CHAdeMO",
      spots: 3,
      rating: 4.6,
      reviews: 72
    },
    {
      id: "chg-002",
      name: "Centro Comercial Nova",
      address: "Calle Mayor 44, Murcia",
      lat: 37.9864,
      lng: -1.1332,
      status: "ocupado",
      type: "estandar",
      power: 22,
      price: 0.23,
      distance: 2.4,
      eta: "2 h 20 min",
      schedule: "08:00 - 23:00",
      connectors: "Tipo 2",
      spots: 0,
      rating: 4.2,
      reviews: 41
    },
    {
      id: "chg-003",
      name: "Universidad Campus Sur",
      address: "Paseo de la Ciencia s/n, Murcia",
      lat: 37.9997,
      lng: -1.1378,
      status: "reparacion",
      type: "rapido",
      power: 50,
      price: 0.26,
      distance: 3.1,
      eta: "45 min",
      schedule: "06:00 - 00:00",
      connectors: "CCS",
      spots: 0,
      rating: 3.8,
      reviews: 15
    },
    {
      id: "chg-004",
      name: "Estacion Intermodal",
      address: "Plaza Estacion 2, Murcia",
      lat: 37.9831,
      lng: -1.1286,
      status: "reservado",
      type: "rapido",
      power: 120,
      price: 0.31,
      distance: 0.9,
      eta: "35 min",
      schedule: "24/7",
      connectors: "CCS, Tesla",
      spots: 1,
      rating: 4.5,
      reviews: 84
    },
    {
      id: "chg-005",
      name: "Parking La Flota",
      address: "Av. de la Flota 9, Murcia",
      lat: 37.9952,
      lng: -1.1195,
      status: "libre",
      type: "estandar",
      power: 11,
      price: 0.19,
      distance: 4.9,
      eta: "3 h",
      schedule: "07:00 - 22:00",
      connectors: "Tipo 2",
      spots: 5,
      rating: 4.1,
      reviews: 33
    },
    {
      id: "chg-006",
      name: "Poligono Industrial Oeste",
      address: "Calle Energia 11, Murcia",
      lat: 37.9724,
      lng: -1.143,
      status: "libre",
      type: "rapido",
      power: 300,
      price: 0.34,
      distance: 7.2,
      eta: "18 min",
      schedule: "24/7",
      connectors: "CCS, CHAdeMO, Tesla",
      spots: 2,
      rating: 4.8,
      reviews: 121
    },
    {
      id: "chg-007",
      name: "Biblioteca Regional",
      address: "Calle del Libro 5, Murcia",
      lat: 37.9874,
      lng: -1.1476,
      status: "ocupado",
      type: "lento",
      power: 7,
      price: 0.15,
      distance: 6.3,
      eta: "5 h",
      schedule: "09:00 - 21:00",
      connectors: "Schuko, Tipo 2",
      spots: 0,
      rating: 3.9,
      reviews: 18
    },
    {
      id: "chg-008",
      name: "Hospital General",
      address: "Ronda Sur 103, Murcia",
      lat: 37.9689,
      lng: -1.1273,
      status: "libre",
      type: "estandar",
      power: 43,
      price: 0.27,
      distance: 8.1,
      eta: "1 h 15 min",
      schedule: "24/7",
      connectors: "CCS, Tipo 2",
      spots: 4,
      rating: 4.4,
      reviews: 56
    }
  ],
  reservations: [
    {
      id: "res-1001",
      chargerId: "chg-001",
      chargerName: "Parking Norte",
      date: "2026-04-03",
      time: "18:00",
      duration: 60,
      status: "activa",
      cost: 9.8
    },
    {
      id: "res-1002",
      chargerId: "chg-005",
      chargerName: "Parking La Flota",
      date: "2026-03-29",
      time: "11:30",
      duration: 120,
      status: "completada",
      cost: 6.4
    },
    {
      id: "res-1003",
      chargerId: "chg-004",
      chargerName: "Estacion Intermodal",
      date: "2026-03-24",
      time: "08:30",
      duration: 45,
      status: "cancelada",
      cost: 0
    }
  ]
};

